[package]
name = "roguelike-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.*"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"